### ISSUE TITLE
Main.panel._boxContainer is undefined

### ISSUE THREAD

**Issue by Satras** [siefkenj/gnome-shell-windowlist#1]
After installing the extension looking glas throws the following error:

error t=2011-10-29T10:03:23Z Extension "windowlist@o2net.cl" had error: Failed to evaluate init function:TypeError: Main.panel._boxContainer is undefined

Gentoo
gnome-shell : 3.2.1
gnome-shell-extensions : 3.2.0

**Comment by siefkenj** [comment]
I just pushed changes to have gnome-shell-windowlist work with 3.2 :-).  Try pulling again.

**Comment by Satras** [comment]
Work's for me!

Nice!

**Comment by siefkenj** [comment]
Opps, I commented a line that I shouldnt have which prevented you from switching the windows by clicking.  It should work now though.
