### ISSUE TITLE
gnome-shell 3.4.1 compatibility

### ISSUE THREAD

**Issue by Lemmiwinks** [siefkenj/gnome-shell-windowlist#12]
For me, this extension is still not compatible with gnome-shell 3.4.1, despite the updates on the code a few days ago. On extensions.gnome.org this extension is still "faded out" and when I want to install it, it shows me the confirmation/install dialog but does not do anything.

**Comment by siefkenj** [comment]
I will be uploading the 3.8 version to extensions.gnome.org shortly.
