### ISSUE TITLE
Gnome-Shell 3.4+ Windows menus are not accessible

### ISSUE THREAD

**Issue by RaphaelRochet** [siefkenj/gnome-shell-windowlist#13]
Since 3.4 (3.3?), gnome-shell introduced window menus. They are not much used yet, but gnome-documents and epiphany for exemple make use of it.

Could you make it so we can still use these menues with your extension ?

**Comment by cloph** [comment]
any suggestion for an alternative? I really desire a windowlist/taskbar - but having to toggle it on and off to make use of the window menus is a real bummer..

**Comment by siefkenj** [comment]
I've now incorporated https://github.com/grossetti/Gnome-Shell-Extensions 's remove app panel, so it should be accessible from the application now.
