### ISSUE TITLE
"violates" Fitts' law - doesn't work with pointer at the very top, need to move down a few pixels

### ISSUE THREAD

**Issue by cloph** [siefkenj/gnome-shell-windowlist#16]
It is not possible to switch to a different window by just moving up the mose at the very top of the screen and moving it over the corresponding entry.

Neither is the entry highlighted accordingly, nor does it swich when actually clicking the mousebutton.
The mousecursor has to be moved a few pixels down to make the entry clickable. This is contrary to the stock entries like Activities, Clock, Battery,...

gnome 3.4.1, windowlist version 4

**Comment by siefkenj** [comment]
Try the current git version.  It should be fixed.

**Comment by cloph** [comment]
yes, fixed - you really should update the copy on extensions.gnome.org :-)
