### ISSUE TITLE
Gnome 3.6 compatibility

### ISSUE THREAD

**Issue by Der-Schubi** [siefkenj/gnome-shell-windowlist#20]
Hi there. Any ideas what has to be changed to get it working on Gnome 3.6?
I just figured out that the code parts for moving the clock have to be updated.
A working 3.6 version for moving the clock is:

const Clutter = imports.gi.Clutter;
const Lang = imports.lang;
const St = imports.gi.St;
const Shell = imports.gi.Shell;

const Main = imports.ui.main;

let dateMenu, label, box;

function init() {
    dateMenu = Main.panel.statusArea.dateMenu;
    label = dateMenu._clock;
}

function enable() {
    Main.panel._centerBox.remove_actor(dateMenu.container);
    Main.panel._addToPanelBox('dateMenu', dateMenu, 0, Main.panel._rightBox);
}

function disable() {

```
Main.panel._rightBox.remove_actor(dateMenu.container);
Main.panel._addToPanelBox('dateMenu', dateMenu, Main.sessionMode.panel.center.indexOf('dateMenu'), Main.panel._centerBox);
```

}

**Comment by siefkenj** [comment]
This is excellent.  With these changes does windowlist run on 3.6?  (I currently don't have 3.6 installed...)  Could you send a pull request with these changes?

**Comment by Der-Schubi** [comment]
Unfortunately It does not, but these changes are necessary too, as the original "move clock" extension wont work on 3.6 until its changed. I'm not firm in debugging these extensions, so I have no idea whats the problem with the rest of the code. But I'll try to learn this in these days.

The problem with my solution to move the clock is, that it will be at the left side of all the status icons, not directly beneath the user menu. But there should be a way to add it into the right box instead!?

You can test Gnome 3.6 with Ubuntu 12.10 Gnome Remix live CD: https://wiki.ubuntu.com/UbuntuGNOME/ReleaseNotes/12.10

**Comment by Der-Schubi** [comment]
OK, Got the list itself working, if I prevent the extension from removing the original AppMenu button. Now I have to figure out how to get rid of this and I try to extend the leftbox, as this extension also doesnt work. Will do a pull request wen im done.

**Comment by Der-Schubi** [comment]
All done :-)
https://github.com/siefkenj/gnome-shell-windowlist/pull/21
