### ISSUE TITLE
Gnome 3.8 compatibility

### ISSUE THREAD

**Issue by orschiro** [siefkenj/gnome-shell-windowlist#25]
Hi, 

Could you please make the extension compatible to Gnome 3.8?

Thanks!

Robert

**Comment by orschiro** [comment]
No problem. Thanks anyway for your extension!

Regards

Robert

**Comment by Der-Schubi** [comment]
It's not mine, but tho original extension isn't developped really active.

Am 23.04.2013 10:30, schrieb Robert Orzanna:

> No problem. Thanks anyway for your extension!
> 
> Regards
> 
> Robert
>

**Comment by Der-Schubi** [comment]
The only thing that's needed for 3.8 support is to update metadata.json.
I did a pull request ;)

**Comment by orschiro** [comment]
Are you sure your request will be pulled?

There is another request waiting for more than a year.

**Comment by Der-Schubi** [comment]
My request for supporting 3.6, 6 months ago was pulled too. So why not.

**Comment by orschiro** [comment]
Ah great. I was just afraid there is no active maintenance anymore.

**Comment by siefkenj** [comment]
For some reason I haven't been getting emails about pull requests...I've merged the metadata.json.  I haven't updated the version on e.g.org in a year because gentoo is still on gnome 3.4 so I haven't been able to test anything new in a year :-/.
