### ISSUE TITLE
Window list not working in gnome-shell 3.3.90

### ISSUE THREAD

**Issue by hvbakel** [siefkenj/gnome-shell-windowlist#6]
After updating the version in metadata.json, the following error appears in .xsession-errors:

JS ERROR: !!!   Exception was: TypeError: imports.ui.extensionSystem.extensions is undefined
JS ERROR: !!!     lineNumber = '34'
JS ERROR: !!!     fileName = '"/home/user/.local/share/gnome-shell/extensions/windowlist@o2net.cl/extension.js"'
JS ERROR: !!!     stack = '"@/home/user/.local/share/gnome-shell/extensions/windowlist@o2net.cl/extension.js:34
"'
JS ERROR: !!!     message = '"imports.ui.extensionSystem.extensions is undefined

**Comment by siefkenj** [comment]
What did you update in the metadata.json?

**Comment by hvbakel** [comment]
I basically just updated the version information:

{
"shell-version": [
   "3.2",
   "3.2.2",
   "3.3.4",
   "3.3.5",
   "3.3.90"
],
"uuid": "windowlist@o2net.cl",
"name": "Window List",
"description": "Add a window list to the top panel",
"url": "https://github.com/siefkenj/gnome-shell-windowlist",
"version": 2
}

**Comment by siefkenj** [comment]
Ah.  There are significant changes in the extensions API for gnome 3.3/3.4.  When 3.4 is released I'll make all the compatibility changes.  It should work with 3.2.2 though.

**Comment by hvbakel** [comment]
I figured as much but thought I'd report it anyway. Thanks for creating and maintaining this wonderful extension!

**Comment by yellowhat** [comment]
Now that gnome-3.4 is out please could you update this wonderful extension for gnome-shell 3.4.

Thanks

**Comment by siefkenj** [comment]
Just merged a patchset for 3.4 compatibility.  Please test before I upload to extensions.gnome.org :-)

**Comment by yellowhat** [comment]
For me works very good.

Thanks
